title:               Faiz Reza
include:             ['_pages']
exclude:             ['_includes/notes_graph.json']
baseurl:             ''

use_html_extension:  false
open_external_links_in_new_tab: true
embed_tweets: false

permalink:           pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-wikilinks        # ‚Üê added plugin

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /:slug        # this is fine and compatible with wikilinks

# Wikilinks configuration
wikilinks:
  collections: ["notes"]     # wikilinks resolve only inside _notes
  html_class: "internal-link" # gives <a class="internal-link">
  # strip_extension: true    # optional if you want to remove .md
  # slugify: true            # optional if note filenames don't match titles

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
